package com.videoclub.pojo;

public enum MovieGenre {
	COMEDY, DRAMA, SCIENCE_FICTION, CRIME, THRILLER, ADVENTURE, SPORT, FAMILY, FANTASY, ACTION, DETECTIVE, HORROR, ROMANCE, BIOGRAPHY, HISTORY, MUSICAL, MYSTERY, WAR, ANIMATION, WESTERN
}
