name: Java CI with Maven (Windows)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'jdk'
        architecture: x64
        check-latest: false
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: success

    - name: Build with Maven
      run: mvnw.cmd clean compile
    
    - name: Run server
      run: mvn jetty:run

    - name: Prepare database for integration tests
      run:  sudo /etc/init.d/mysql start
      
    - name: Enhance database
      run: mvn datanucleus:enhance 
    - name: Create schema
      run: mvn datanucleus:schema-create

    - name: Execute tests
      run: mvn test

    - name: Run client
      run: mvn exec:java -Pclient
