name: Java CI wiith Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Prepare database for integration tests
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < sql/videoclubdb.sql
          mvn --batch-mode --update-snapshots datanucleus:enhance datanucleus:schema-create

      - name: Start server
        run: |
          sudo apt-get install -y tmux
          tmux new-session -d -s server "mvn --batch-mode --update-snapshots jetty:run"

      - name: Run tests
        run: |
          tmux new-session -d -s tests "mvn --batch-mode --update-snapshots test"
